---
name: w1

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main


jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: sha
        run: |
          echo github.sha ${{ github.sha }}
          echo github.ref ${{ github.ref }}
          echo github.head_ref ${{ github.head_ref }}
          echo github.base_ref ${{ github.base_ref }}
          echo github.event.number ${{ github.event.number }}
